### ISSUE TITLE
As an end-user, I want to be able to write to modbus registers

### ISSUE THREAD

**Issue by mhemeryck** [mhemeryck/modbridge#29]
Support for writing to modbus registers from MQTT events.

**Comment by pki791** [comment]
mhemeryck, have You found a solution for bidirectional modbus<>mqtt gateway?

**Comment by mhemeryck** [comment]
@pki791 not really; the best setup I currently have is to use modbus between the unipi modules and an MQTT interface which just uses unipi's evok library. See https://blog.mhemeryck.com/2021-11-16/modbusbackup (and related posts) for an overview.
